export const LOAD_THEME = 'LOAD_THEME';
export const APPLY_THEME_SUCCESS = 'APPLY_THEME_SUCCESS';

export const UPDATE_GAME_SCORE = 'UPDATE_GAME_SCORE';
export const UPDATE_GAME_HIGH_SCORE = 'UPDATE_GAME_HIGH_SCORE';
export const RESET_GAME_SCORE = 'RESET_GAME_SCORE';
